//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.passwordTester {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="passwordTester.IPasswordTester")]
    public interface IPasswordTester {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordTester/checkPassword", ReplyAction="http://tempuri.org/IPasswordTester/checkPasswordResponse")]
        int checkPassword(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordTester/checkPassword", ReplyAction="http://tempuri.org/IPasswordTester/checkPasswordResponse")]
        System.Threading.Tasks.Task<int> checkPasswordAsync(string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPasswordTesterChannel : Proyecto.passwordTester.IPasswordTester, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordTesterClient : System.ServiceModel.ClientBase<Proyecto.passwordTester.IPasswordTester>, Proyecto.passwordTester.IPasswordTester {
        
        public PasswordTesterClient() {
        }
        
        public PasswordTesterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordTesterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordTesterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordTesterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int checkPassword(string password) {
            return base.Channel.checkPassword(password);
        }
        
        public System.Threading.Tasks.Task<int> checkPasswordAsync(string password) {
            return base.Channel.checkPasswordAsync(password);
        }
    }
}
